version: '3'

services:
  broker-service:
    build:
      context: ../broker-service
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:80
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - postgres
  
  auth-service:
    build:
      context: ../authentication-service
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8081:80
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: "host=postgres port=5432 user=postgres password=password dbname=postric sslmode=disable timezone=UTC connect_timeout=5"
    depends_on:
      - postgres
  
  postgres:
    image: postgres:14.2
    ports:
      - 5432:5432
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postric
    volumes:
      - pg-postric:/var/lib/postgresql/data/

volumes:
  pg-postric:
